<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQe2QsLA\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQe2QsLA/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerQe2QsLA.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerQe2QsLA\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerQe2QsLA\App_KernelProdContainer([
    'container.build_hash' => 'Qe2QsLA',
    'container.build_id' => '4ad6c5ad',
    'container.build_time' => 1684427907,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQe2QsLA');
