<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'examen.examen' => [[], ['_controller' => 'App\\Controller\\ExamenController::examen'], [], [['text', '/examen/']], [], [], []],
    'examen.question' => [['passerExamenId', 'number'], ['_controller' => 'App\\Controller\\ExamenController::question'], [], [['variable', '/', '[^/]++', 'number', true], ['text', '/question'], ['variable', '/', '[^/]++', 'passerExamenId', true], ['text', '/examen']], [], [], []],
    'examen.response' => [['passerExamenId', 'questionId', 'number'], ['_controller' => 'App\\Controller\\ExamenController::setResponse'], [], [['variable', '/', '[^/]++', 'number', true], ['variable', '/', '[^/]++', 'questionId', true], ['variable', '/', '[^/]++', 'passerExamenId', true], ['text', '/examen/setResponse']], [], [], []],
    'examen.resultat' => [['passerExamenId'], ['_controller' => 'App\\Controller\\ExamenController::score'], [], [['text', '/score'], ['variable', '/', '[^/]++', 'passerExamenId', true], ['text', '/examen']], [], [], []],
    'examen.reponse_correct' => [['passerExamenId', 'number'], ['_controller' => 'App\\Controller\\ExamenController::reponse'], [], [['variable', '/', '[^/]++', 'number', true], ['text', '/reponse'], ['variable', '/', '[^/]++', 'passerExamenId', true], ['text', '/examen']], [], [], []],
    'app_lessons' => [[], ['_controller' => 'App\\Controller\\LessonsController::index'], [], [['text', '/lessons']], [], [], []],
    'login' => [[], ['_controller' => 'App\\Controller\\LoginController::index'], [], [['text', '/login']], [], [], []],
    'app_main' => [[], ['_controller' => 'App\\Controller\\MainController::home'], [], [['text', '/']], [], [], []],
    'question_all' => [[], ['_controller' => 'App\\Controller\\QuestionController::all'], [], [['text', '/question/all']], [], [], []],
    'questionapp_question_add' => [[], ['_controller' => 'App\\Controller\\QuestionController::add'], [], [['text', '/question/add']], [], [], []],
    'app_register' => [[], ['_controller' => 'App\\Controller\\RegistrationController::register'], [], [['text', '/register']], [], [], []],
    'users.all_users' => [[], ['_controller' => 'App\\Controller\\UserController::index'], [], [['text', '/user/all']], [], [], []],
    'users.modifier_user' => [['id'], ['_controller' => 'App\\Controller\\UserController::update'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/user/modifier']], [], [], []],
    'users.supprimer_user' => [['id'], ['_controller' => 'App\\Controller\\UserController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/user/supprimer']], [], [], []],
    'users.app_history' => [['userId'], ['_controller' => 'App\\Controller\\UserController::historique'], [], [['text', '/historique'], ['variable', '/', '[^/]++', 'userId', true], ['text', '/user']], [], [], []],
];
