<?php

namespace ContainerNGIw7kM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_XMCPb0Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.X_mCPb0' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.X_mCPb0'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'passerRepo' => ['privates', 'App\\Repository\\PasserExamenRepository', 'getPasserExamenRepositoryService', true],
        ], [
            'passerRepo' => 'App\\Repository\\PasserExamenRepository',
        ]);
    }
}
