<?php

namespace ContainerQe2QsLA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getArgumentResolver_ServiceService extends App_KernelProdContainer
{
    /*
     * Gets the private 'argument_resolver.service' shared service.
     *
     * @return \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\ExamenController::examen' => ['privates', '.service_locator.ZsaSdmr', 'get_ServiceLocator_ZsaSdmrService', true],
            'App\\Controller\\ExamenController::question' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'App\\Controller\\ExamenController::reponse' => ['privates', '.service_locator..Z2Pysp', 'get_ServiceLocator__Z2PyspService', true],
            'App\\Controller\\ExamenController::score' => ['privates', '.service_locator..Z2Pysp', 'get_ServiceLocator__Z2PyspService', true],
            'App\\Controller\\ExamenController::setResponse' => ['privates', '.service_locator.Pk8FRvi', 'get_ServiceLocator_Pk8FRviService', true],
            'App\\Controller\\LessonsController::index' => ['privates', '.service_locator.kPdovlX', 'get_ServiceLocator_KPdovlXService', true],
            'App\\Controller\\QuestionController::add' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'App\\Controller\\QuestionController::all' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.e_4zbH4', 'get_ServiceLocator_E4zbH4Service', true],
            'App\\Controller\\UserController::delete' => ['privates', '.service_locator.LLEuAX_', 'get_ServiceLocator_LLEuAXService', true],
            'App\\Controller\\UserController::historique' => ['privates', '.service_locator.yqE9B.3', 'get_ServiceLocator_YqE9B_3Service', true],
            'App\\Controller\\UserController::index' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'App\\Controller\\UserController::update' => ['privates', '.service_locator.0yAOTZk', 'get_ServiceLocator_0yAOTZkService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\ExamenController:examen' => ['privates', '.service_locator.ZsaSdmr', 'get_ServiceLocator_ZsaSdmrService', true],
            'App\\Controller\\ExamenController:question' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'App\\Controller\\ExamenController:reponse' => ['privates', '.service_locator..Z2Pysp', 'get_ServiceLocator__Z2PyspService', true],
            'App\\Controller\\ExamenController:score' => ['privates', '.service_locator..Z2Pysp', 'get_ServiceLocator__Z2PyspService', true],
            'App\\Controller\\ExamenController:setResponse' => ['privates', '.service_locator.Pk8FRvi', 'get_ServiceLocator_Pk8FRviService', true],
            'App\\Controller\\LessonsController:index' => ['privates', '.service_locator.kPdovlX', 'get_ServiceLocator_KPdovlXService', true],
            'App\\Controller\\QuestionController:add' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'App\\Controller\\QuestionController:all' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.e_4zbH4', 'get_ServiceLocator_E4zbH4Service', true],
            'App\\Controller\\UserController:delete' => ['privates', '.service_locator.LLEuAX_', 'get_ServiceLocator_LLEuAXService', true],
            'App\\Controller\\UserController:historique' => ['privates', '.service_locator.yqE9B.3', 'get_ServiceLocator_YqE9B_3Service', true],
            'App\\Controller\\UserController:index' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'App\\Controller\\UserController:update' => ['privates', '.service_locator.0yAOTZk', 'get_ServiceLocator_0yAOTZkService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\ExamenController::examen' => '?',
            'App\\Controller\\ExamenController::question' => '?',
            'App\\Controller\\ExamenController::reponse' => '?',
            'App\\Controller\\ExamenController::score' => '?',
            'App\\Controller\\ExamenController::setResponse' => '?',
            'App\\Controller\\LessonsController::index' => '?',
            'App\\Controller\\QuestionController::add' => '?',
            'App\\Controller\\QuestionController::all' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\UserController::delete' => '?',
            'App\\Controller\\UserController::historique' => '?',
            'App\\Controller\\UserController::index' => '?',
            'App\\Controller\\UserController::update' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\ExamenController:examen' => '?',
            'App\\Controller\\ExamenController:question' => '?',
            'App\\Controller\\ExamenController:reponse' => '?',
            'App\\Controller\\ExamenController:score' => '?',
            'App\\Controller\\ExamenController:setResponse' => '?',
            'App\\Controller\\LessonsController:index' => '?',
            'App\\Controller\\QuestionController:add' => '?',
            'App\\Controller\\QuestionController:all' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\UserController:delete' => '?',
            'App\\Controller\\UserController:historique' => '?',
            'App\\Controller\\UserController:index' => '?',
            'App\\Controller\\UserController:update' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]));
    }
}
