<?php

namespace ContainerQe2QsLA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getExamenRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\ExamenRepository' shared autowired service.
     *
     * @return \App\Repository\ExamenRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\ExamenRepository'] = new \App\Repository\ExamenRepository(($container->services['doctrine'] ?? $container->load('getDoctrineService')));
    }
}
