<?php

namespace ContainerQe2QsLA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getExamenControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\ExamenController' shared autowired service.
     *
     * @return \App\Controller\ExamenController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\ExamenController'] = $instance = new \App\Controller\ExamenController();

        $instance->setContainer(($container->privates['.service_locator.CshazM0'] ?? $container->load('get_ServiceLocator_CshazM0Service'))->withContext('App\\Controller\\ExamenController', $container));

        return $instance;
    }
}
