<?php

namespace ContainerQe2QsLA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPasserExamenRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\PasserExamenRepository' shared autowired service.
     *
     * @return \App\Repository\PasserExamenRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\PasserExamenRepository'] = new \App\Repository\PasserExamenRepository(($container->services['doctrine'] ?? $container->load('getDoctrineService')));
    }
}
