<?php

namespace ContainerQe2QsLA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getQuestionControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\QuestionController' shared autowired service.
     *
     * @return \App\Controller\QuestionController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\QuestionController'] = $instance = new \App\Controller\QuestionController();

        $instance->setContainer(($container->privates['.service_locator.CshazM0'] ?? $container->load('get_ServiceLocator_CshazM0Service'))->withContext('App\\Controller\\QuestionController', $container));

        return $instance;
    }
}
