<?php

namespace ContainerQe2QsLA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserServiceService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Service\userService' shared autowired service.
     *
     * @return \App\Service\userService
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Service\\userService'] = new \App\Service\userService();
    }
}
