<?php

namespace ContainerPO384xY;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_7rSnXY9Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.7rSnXY9' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.7rSnXY9'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'questionRepo' => ['privates', 'App\\Repository\\QuestionRepository', 'getQuestionRepositoryService', true],
            'sec' => ['privates', 'security.helper', 'getSecurity_HelperService', true],
            'userRepo' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'em' => '?',
            'questionRepo' => 'App\\Repository\\QuestionRepository',
            'sec' => '?',
            'userRepo' => 'App\\Repository\\UserRepository',
        ]);
    }
}
