<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNGIw7kM\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNGIw7kM/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNGIw7kM.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNGIw7kM\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNGIw7kM\App_KernelDevDebugContainer([
    'container.build_hash' => 'NGIw7kM',
    'container.build_id' => 'edd6016c',
    'container.build_time' => 1716080444,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNGIw7kM');
