<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'app_categories' => [[], ['_controller' => 'App\\Controller\\CategorieController::index'], [], [['text', '/categories']], [], [], []],
    'app_lessons_list' => [['id'], ['_controller' => 'App\\Controller\\CategorieController::lessons'], [], [['text', '/lessons'], ['variable', '/', '[^/]++', 'id', true]], [], [], []],
    'examen.examen' => [[], ['_controller' => 'App\\Controller\\ExamenController::examen'], [], [['text', '/examen/']], [], [], []],
    'examen.question' => [['passerExamenId', 'number'], ['_controller' => 'App\\Controller\\ExamenController::question'], [], [['variable', '/', '[^/]++', 'number', true], ['text', '/question'], ['variable', '/', '[^/]++', 'passerExamenId', true], ['text', '/examen']], [], [], []],
    'examen.response' => [['passerExamenId', 'questionId', 'number'], ['_controller' => 'App\\Controller\\ExamenController::setResponse'], [], [['variable', '/', '[^/]++', 'number', true], ['variable', '/', '[^/]++', 'questionId', true], ['variable', '/', '[^/]++', 'passerExamenId', true], ['text', '/examen/setResponse']], [], [], []],
    'examen.resultat' => [['passerExamenId'], ['_controller' => 'App\\Controller\\ExamenController::score'], [], [['text', '/score'], ['variable', '/', '[^/]++', 'passerExamenId', true], ['text', '/examen']], [], [], []],
    'examen.reponse_correct' => [['passerExamenId', 'number'], ['_controller' => 'App\\Controller\\ExamenController::reponse'], [], [['variable', '/', '[^/]++', 'number', true], ['text', '/reponse'], ['variable', '/', '[^/]++', 'passerExamenId', true], ['text', '/examen']], [], [], []],
    'app_add_lesson' => [[], ['_controller' => 'App\\Controller\\LessonsController::add'], [], [['text', '/lessons/add']], [], [], []],
    'app_lessons_all' => [[], ['_controller' => 'App\\Controller\\LessonsController::all'], [], [['text', '/lessons/all']], [], [], []],
    'app_delete_lesson' => [['id'], ['_controller' => 'App\\Controller\\LessonsController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/lessons/supprimer']], [], [], []],
    'app_login' => [[], ['_controller' => 'App\\Controller\\LoginController::index'], [], [['text', '/login']], [], [], []],
    'app_logout' => [[], ['_controller' => 'App\\Controller\\LoginController::logout'], [], [['text', '/logout']], [], [], []],
    'app_main' => [[], ['_controller' => 'App\\Controller\\MainController::home'], [], [['text', '/']], [], [], []],
    'app_history' => [[], ['_controller' => 'App\\Controller\\MainController::historique'], [], [['text', '/historique']], [], [], []],
    'app_delete_history' => [['id'], ['_controller' => 'App\\Controller\\MainController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/historique/delete']], [], [], []],
    'question_all' => [[], ['_controller' => 'App\\Controller\\QuestionController::all'], [], [['text', '/question/all']], [], [], []],
    'questionapp_question_add' => [[], ['_controller' => 'App\\Controller\\QuestionController::add'], [], [['text', '/question/add']], [], [], []],
    'question_modifier' => [['id'], ['_controller' => 'App\\Controller\\QuestionController::update'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/question/modifier']], [], [], []],
    'question_supprimer' => [['id'], ['_controller' => 'App\\Controller\\QuestionController::delete'], [], [['text', '/'], ['variable', '/', '[^/]++', 'id', true], ['text', '/questionsupprimer']], [], [], []],
    'app_register' => [[], ['_controller' => 'App\\Controller\\RegistrationController::register'], [], [['text', '/register']], [], [], []],
    'app_password' => [['id'], ['_controller' => 'App\\Controller\\RegistrationController::changePassword'], [], [['text', '/change-password'], ['variable', '/', '[^/]++', 'id', true]], [], [], []],
    'users.all_users' => [[], ['_controller' => 'App\\Controller\\UserController::index'], [], [['text', '/user/all']], [], [], []],
    'users.modifier_user' => [['id'], ['_controller' => 'App\\Controller\\UserController::update'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/user/modifier']], [], [], []],
    'users.supprimer_user' => [['id'], ['_controller' => 'App\\Controller\\UserController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/user/supprimer']], [], [], []],
    'users.add_user' => [[], ['_controller' => 'App\\Controller\\UserController::add'], [], [['text', '/user/add']], [], [], []],
];
